[package]
name = "lv-kiosk"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "lv-kiosk"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap.workspace = true
csv.workspace = true
iced.workspace = true
image.workspace = true
lv-core.workspace = true
lv-mdb.workspace = true
lv-ui.workspace = true
lv-vendimint.workspace = true
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
